MVCCrud/MVCCrud/Models/ViewModels/TablaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCCrud.Models.ViewModels
{
    public class TablaViewModel
    {

        //Recibe los elementos
        public int Id { get; set; }

        //Datanotation para hacer validaciones
        [Required]
        //Validacion
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }

        [Required]
        [StringLength(50)]
        //Valida que es un correo
        [EmailAddress]
        [Display(Name = "Correo electrónico")]
        public string Correo { get; set; }

        [Required]
        //Tipo del editorford (Date)
        [DataType(DataType.Date)] 
        [Display(Name = "Fecha de nacimiento")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime Fecha_Nacimiento { get; set; }





    }
}

MVCCrud/MVCCrud/Models/tabla.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
    }
}

MVCCrud/MVCCrud/Controllers/TablaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCCrud.Models.ViewModels;
//Obtiene los elementos a partir de Entityframework
using MVCCrud.Models;


namespace MVCCrud.Controllers
{
    public class TablaController : Controller
    {
        // GET: Tabla
        public ActionResult Index()
        {

            //Saca la lista
            List<ListTablaViewModel> lst;


            //Uso del contexto entities. Conexion a la BD
            using (CrudEntities db = new CrudEntities())
            {

                //Obtiene el listado de los elementos
                lst = (from d in db.tabla

                       select new ListTablaViewModel

                       {
                           Id = d.id,
                           Nombre = d.nombre,
                           Correo = d.correo

                       }).ToList();
            }    

            //Manda la lista como modelo a su vista
            return View(lst);
        }

        //Metodo nuevo
        public ActionResult Nuevo()
        {

            return View();

        }

            public ActionResult Inicio()
        {
            return View();
        }

        //Metodo nuevo que ejecuta el boton guardar
        [HttpPost]
        public ActionResult Nuevo(TablaViewModel model)
        {
            //El try regresa el error si existe
            try
            {

                //Valida los datanotation que son requeridos y ahi empieza la programacion
                if(ModelState.IsValid)
                {

                 
                    using (CrudEntities db = new CrudEntities())
                    {

                        //Creacion del objeto tabla(o)
                        var oTabla = new tabla();

                        
                        oTabla.nombre = model.Nombre;
                        oTabla.correo = model.Correo;
                        oTabla.fecha_nacimiento = model.Fecha_Nacimiento;

                        //Guarda en la BD la informacion
                        db.tabla.Add(oTabla);
                        db.SaveChanges();

                    }

                    //Regresa a la vista donde esta el listado
                    return Redirect("~/Tabla/");

                }
                return View(model);

            }

            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }

        
        //Metodo editar

        //int ID recibe al ID
        public ActionResult Editar(int Id)

        {
            //Se manda el modelo a partir de la BD
            TablaViewModel model = new TablaViewModel();
            using(CrudEntities db = new CrudEntities())

            {
                //Se obtienen los elementos de ID
                var oTabla = db.tabla.Find(Id);

                //Llena los modelos ID, NOMBRE, CORREO Y FECHA
                
                //Se manda el ID al modelo para saber cual se va a editar
                model.Id = oTabla.id;
                model.Nombre = oTabla.nombre;
                model.Correo = oTabla.correo;
                model.Fecha_Nacimiento = oTabla.fecha_nacimiento;

                

            }

            return View(model);

        }
        
          
        //Metodo editar con cod. programacion
        [HttpPost]
        public ActionResult Editar(TablaViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CrudEntities db = new CrudEntities())
                    {
                        var oTabla = db.tabla.Find(model.Id);
                        oTabla.nombre = model.Nombre;
                        oTabla.correo = model.Correo;
                        oTabla.fecha_nacimiento = model.Fecha_Nacimiento;

                        db.Entry(oTabla).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }
                    return Redirect("~/Home/");
                }
                return View(model);
            }

            catch(Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }

        //Solicitud para eliminar
        [HttpGet]

        public ActionResult Eliminar (int Id)

        {

            using (CrudEntities db = new CrudEntities())
            {

                var oTabla = db.tabla.Find(Id);

                //Elimina la entidad (tabla)
                db.tabla.Remove(oTabla);
                //Guarda
                db.SaveChanges();
            }

            //Redirect al listado
            return Redirect("~/Tabla/");

           
        }

  

    }
 }


 











 

MVCCrud/MVCCrud/Views/Tabla/Editar.cshtml
@model MVCCrud.Models.ViewModels.TablaViewModel
@{
    ViewBag.Title = "Editar";
}

<h2>@ViewBag.Title</h2>
@using (Html.BeginForm("Editar", "Tabla", FormMethod.Post))


{
    <div class="row">
        <div class="col-md-12">

            @*Cod. para guardar el ID*@
            @Html.HiddenFor(d => d.Id)


            @*Automaticamente se llenan los controles*@
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>




            <div>
                @Html.LabelFor(d => d.Correo)
                @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
            </div>

            <div>

                @Html.LabelFor(d => d.Fecha_Nacimiento)<br />
                @Html.EditorFor(d => d.Fecha_Nacimiento, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Fecha_Nacimiento, null, new { @class = "red" })
            </div>


            <br />

            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />

            </div>


        </div>
    </div>
}

MVCCrud/MVCCrud/Views/Tabla/Index.cshtml
<!--Recibe la lista-->
@model List<MVCCrud.Models.ViewModels.ListTablaViewModel>

@{
    ViewBag.Title = "Mis datos";

}

<!--Se utiliza bootstrap para darle elstilo-->



<h2>@ViewBag.Title</h2>
<a class="nav-link text-dark" href="~/Tabla/Inicio"><font color="black">Pantalla principal</font></a>
<!--Boton nuevo-->
<div class="row" style="text-align:right; padding:5px;">
    <a href="~/Tabla/Nuevo" class="btn btn-primary">Nuevo</a>
</div>

<div class="row" style="text-align:left; padding:5px;">
    <a href="~/Vida/Nuevo" class="btn btn-primary">Vida</a>
</div>


<div class="row">
    <!--Listado de 12 columnas-->
    <div class="col-md-12">
        <!--Creacion de la tabla-->
        <table class="table">

            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Correo</th>
            </tr>

            <!--Foreach para traer los datos-->
            @foreach (var oElemento in Model)
            {
                <tr>
                    <td>@oElemento.Id</td>
                    <td>@oElemento.Nombre</td>
                    <td>@oElemento.Correo</td>

                    <td>
                        @*Creacion de los botones*@
                        <a class="btn btn-default" href="~/Tabla/Editar/@oElemento.Id">Editar</a>
                        <a class="btn btn-danger" href="~/Tabla/Eliminar/@oElemento.Id">Eliminar</a>

                    </td>

                </tr>




            }



        </table>

    </div>
</div>

MVCCrud/MVCCrud/Views/Tabla/Inicio.cshtml
@{
    ViewBag.Title = "Inicio";
}

<h2>Inicio</h2>

<p>HOLAAAAAAAAAAAAAAAAAAAAAA</p>

MVCCrud/MVCCrud/Views/Tabla/Nuevo.cshtml
<!--Recibe el modelo que viene en blanco-->
@model MVCCrud.Models.ViewModels.TablaViewModel
@{
    ViewBag.Title = "Nuevo";
}
<h2>@ViewBag.Title</h2>


<!--Creacion del formulario-->
@using (Html.BeginForm("Nuevo", "Tabla", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-12">

            <!--Se agregan los componentes (Nombre, correo, y fecha)-->

            @*Div para agrupar cada elemento*@
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
                <br /> <br /> 
            </div>            
            
            <div>
                @Html.LabelFor(d => d.Correo)
                @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
                <br /> <br />  
            </div>

            <div>
               
                @Html.LabelFor(d => d.Fecha_Nacimiento)<br />
                @Html.EditorFor(d => d.Fecha_Nacimiento, "", new { @class = "form-control" })<br/>

                @*Helper que indica errores*@
                @Html.ValidationMessageFor(d => d.Fecha_Nacimiento, null, new { @class = "red" })
            </div>

            <br/>

            <!--Creacion del boton guardar-->
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />
            </div>

        </div>
    </div>
}